const mongoose = require("mongoose");

var EffortEstimationSchema = new mongoose.Schema({
    rpatool:{
        type:String,
        required:"Required"
    },
    Simple: {
        type:Number,
        required:"Required"
    },
    Medium: {
        type:Number,
        required:"Required"
    },
    Complex: {
        type:Number,
        required:"Required"
    },
    Total: {
        type:Number,
        required:"Required"
    },
    Simple_Dev_Effort: {
        type:Number,
        required:"Required"
    },
    Simple_Srdev_Effort: {
        type:Number,
        required:"Required"
    },
         
    Simple_BA_Effort: {
        type:Number,
        required:"Required"
    },
    Simple_Arch_Effort: {
        type:Number,
        required:"Required"
    },
    Simple_PM_Effort: {
        type:Number,
        required:"Required"
    },
    Simple_DM_Effort: {
        type:Number,
        required:"Required"
    },
    Total_Simple_Effort: {
        type:Number,
        required:"Required"
    },
    Medium_Dev_Effort: {
        type:Number,
        required:"Required"
    },
         
    Medium_Srdev_Effort: {
        type:Number,
        required:"Required"
    },
    Medium_BA_Effort: {
        type:Number,
        required:"Required"
    },
    Medium_Arch_Effort: {
        type:Number,
        required:"Required"
    },
    Medium_PM_Effort: {
        type:Number,
        required:"Required"
    },
    Medium_DM_Effort: {
        type:Number,
        required:"Required"
    },
    Total_Medium_Effort: {
        type:Number,
        required:"Required"
    },
    Complex_Dev_Effort:{
        type:Number,
        required:"Required"
    },
    Complex_Srdev_Effort:{
        type:Number,
        require:"Required"
    },
    Complex_BA_Effort:{
        type:Number,
        required:"Required"
    },
    Complex_Arch_Effort:{
        type:Number,
        required:"Required"
    },
    Complex_PM_Effort:{
        type:Number,
        required:"Required"
    },
    Complex_DM_Effort:{
        type:Number,
        required:"Required"
    },
    Total_Complex_Effort:{
        type:Number,
        required:"Required"
    },
    Total_Dev_Effort:{
        type:Number,
        required:"Required"
    },
    Total_Srdev_Effort:{
        type:Number,
        required:"Required"
    },
    Total_BA_Effort:{
        type:Number,
        required:"Required"
    },
    Total_Arch_Effort:{
        type:Number,
        required:"Required"
    },
    Total_PM_Effort:{
        type:Number,
        required:"Required"
    },
    Total_DM_Effort:{
        type:Number,
        required:"Required"
    },
    Total_Of_Total_Effort:{
        type:Number,
        required:"Required"
    },
    Dev_Roundoff:{
        type:Number,
        required:"Required"
    },
    Srdev_Roundoff:{
        type:Number,
        required:"Required"
    },
    BA_Roundoff:{
        type:Number,
        required:"Required"
    },
    Arch_Roundoff:{
        type:Number,
        required:"Required"
    },
    PM_Roundoff:{
        type:Number,
        required:"Required"
    },
    DM_Roundoff:{
        type:Number,
        required:"Required"
    },
    Dev_Cost:{
        type:Number,
        required:"Required"
    },
    Srdev_Cost:{
        type:Number,
        required:"Required"
    },
    BA_Cost:{
        type:Number,
        required:"Required"
    },
    Arch_Cost:{
        type:Number,
        required:"Required"
    },
    PM_Cost:{
        type:Number,
        required:"Required"
    },
    DUlead_Cost_:{
        type:Number,
        required:"Required"
    },
    Total_Imp_Cost:{
        type:Number,
        required:"Required"

    },
    Bot_Creator_Count:{
        type:Number,
        required:"Required"
    },
    Bot_Creator_Price:{
        type:Number,
        required:"Required"
    },
    Total_Bot_Creator_Cost:{
        type:Number,
        required:"Required"
    },
    Botrunner_Unatt_Count:{
        type:Number,
        required:"Required"
    },
    Botrunner_Unatt_Price:{
        type:Number,
        required:"Required"
    },
    Total_Botrunner_Unatt_Cost:{
        type:Number,
        required:"Required"
    },
    Botrunner_Att_Count:{
        type:Number,
        required:"Required"
    },
    Botrunner_Att_Price:{
        type:Number,
        required:"Required"
    },
    Total_Botrunner_Att_Cost:{
        type:Number,
        required:"Required"
    },
    Controlroom_Count:{
        type:Number,
        required:"Required"
    },
    Controlroom_Price:{
        type:Number,
        required:"Required"
    },
    Total_Controlroom_Cost:{
        type:Number,
        required:"Required"
    },
    Totalof_Total_Lisc_Price:{
        type:Number,
        required:"Required"
    },
    VM_Count:{
        type:Number,
        required:"Required"
    },
    VM_Price:{
        type:Number,
        required:"Required"
    },
    Total_VM_Price:{
        type:Number,
        required:"Required"
    },
    Server_Count:{
        type:Number,
        required:"Required"
    },
    Server_Price:{
        type:Number,
        required:"Required"
    },
    Total_Server_Price:{
        type:Number,
        required:"Required"
    },
    Totalof_Total_Infra_Price:{
        type:Number,
        required:"Required"
    },
    Maint_Cost:{
        type:Number,
        required:"Required"
    },
    FTE_Savings_Count:{
        type:Number,
        required:"Required"
    },
    Controlroom_Count:{
        type:Number,
        required:"Required"
    },
    FTE_Price:{
        type:Number,
        required:"Required"
    },
    FTE_Savings_USD:{
        type:Number,
        required:"Required"
    },
    Net_Savings:{
        type:Number,
        required:"Required"
    },
    Net_Savings_Two:{
        type:Number,
        required:"Required"
    },
    Total_Imp_Cost_Two_:{
        type:String,
        required:"Required"
    },
    Total_TCO_Two_:{
        type:String,
        required:"Required"
    },
    Total_Net_Savings_Two_:{
        type:String,
        required:"Required"
    },
   BI:{
        type:String,
        required:"Required"
    },
   rx:{
        type:String,
        required:"Required"
    },
    pid:{
        type:String,
        required:"Required"
    },
    pd:{
        type:Number,
        required:"Required"
    }

},
    {
        toObject: {
          virtuals: true,
        },
        toJSON: {
          virtuals: true,
        },
});

mongoose.model('EffortEstimation', EffortEstimationSchema);
